services:
  mlflow:
    build: .
    container_name: mlflow-server
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=require
      --artifacts-destination wasbs://${BLOB_CONTAINER}@${STORAGE_ACCOUNT}.blob.core.windows.net/
      --host 0.0.0.0
      --port 5000
