name: Azure Login Test

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  azure-login:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
